<?php 
$data2 = [
    "lists" => [
        [
            "name" => "United States(US)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "PayPal Credit (Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "Venmo",
                "APM - Trustly (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, PPC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout, ACDC",
            ],
        ],
        [
            "name" => "Canada(CA)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout, ACDC",
            ],
        ],
        [
            "name" => "United Kingdom(GB)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "PayPal Credit (Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, PPC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout, PPC",
            ],
        ],
        [
            "name" => "Austria(AT)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly",
                "APM - eps",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Belgium(BE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Bancontact",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Bulgaria(BG)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Cyprus(CY)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Czech Republic(CZ)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Denmark(DK)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],

        [
            "name" => "Estonia(EE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Finland(FI)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],

        [
            "name" => "France(FR)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Germany(DE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "APM - Trustly",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Greece(GR)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Hungary(HU)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Ireland(IE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Italy(IT)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "APM - MyBank",
                "APM - Satispay in Beta",
                "APM - BANCOMAT Pay - Beta for Direct Merchants",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Latvia(LT)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Liechtenstein(LI)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Lithuania(LT)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "ACH Direct Debit",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Luxembourg(LU)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ], 
        [
            "name" => "Malta(MT)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ], 
        [
            "name" => "Netherlands(NL)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - iDEAL",
                "APM - Trustly",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Zettle POS",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ], 
        [
            "name" => "Norway(NO)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Poland(PL)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - BLIK",
                "APM - Przelewy24",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Portugal(PT)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Multibanco",
                "APM - MB Way in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Romania(RO)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Slovakia(SK)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Slovenia(SI)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Spain(ES)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "APM - Trustly (Buyer Country)",
                "APM - Satispay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Sweden(SE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Trustly (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "Virtual Terminal (MAM merchants only)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "IC++ Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal, Guest Checkout - Domestic only",
            ],
        ],
        [
            "name" => "Andorra(AD)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Croatia(HR)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Iceland(IS)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Monaco(MC)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country) - CBT",
                "Payouts (Receiver Country) - CBT",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "San Marino(SM)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Satispay in Beta",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Switzerland(CH)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Australia(AU)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Pay Later(Buyer Country)",
                "Pay Later Messaging (Buyer and Merchant Country) * XB not supported",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "3PNT - Beta",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, BNPL, Apple Pay",
                "Subscription APIs - PayPal, ACDC",
            ],
        ], 
        [
            "name" => "China(CN)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal - Cross Border",
                "Advanced Card Payments(ACDC) - Cross Border",
                "Apple Pay - Cross Border",
                "Google Pay - Cross Border",
                "Partner Fee (Partner Country) - Wire",
                 "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country) - CBT",
                "Invoicing APIs (Buyer Country) - PayPal and Apple Pay - CBT",
                "Subscription APIs - PayPal and Guest Checkout - CBT",
            ],
        ],
        [
            "name" => "Hong Kong(HK)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ], 
        [
            "name" => "India(IN)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "PayPal - Cross Border",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country) - CBT",
                "Payouts (Receiver Country) - CBT",
                "Invoicing APIs (Buyer Country) - PayPal - CBT",
                "Subscription APIs - PayPal - CBT",
            ],
        ],
        [
            "name" => "Indonesia(ID)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding (PayPal)",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Japan(JP)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding (PayPal)",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "RTAU - Real Time Account Updater (Merchant Country)",
                "MCP",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ], 
        [
            "name" => "Korea(KR)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Malaysia(MY)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW - Only Malaysian Banks",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "New Zealand(NZ)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Phillippines(PH)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Singapore(SG)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Grabpay in Beta",
                "Advanced Card Payments(ACDC)",
                "Apple Pay",
                "Google Pay",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "Vaulting with Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting without Purchase (Merchant Level) *ISU Upfront Onboarding only",
                "Vaulting with Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "Vaulting without Purchase (Partner Level) *ISU Upfront and MAM Onboarding",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC, Apple Pay",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Taiwan(TW)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Thailand(TH)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Vietnam(VN)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country) - Wire",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Brazil(BR)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - Boleto Bancario - Beta for Direct Merchants",
                "Zettle POS",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Mexico(MX)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Business Account - Full Stack",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "APM - OXXO Beta - Direct Merchants",
                "Advanced Card Payments(ACDC)",
                "Zettle POS",
                "Partner Fee (Partner Country)",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "MCW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Argentina(AR)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country) - Wire",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Colombia(CO)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country) - Wire",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Peru(PE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country) - Wire",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal, Guest Checkout",
            ],
        ],
        [
            "name" => "Chile(CL)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country) - Wire",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Bahrain(BH)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Botswana(BW)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Egypt(EG)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Georgia(GE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Jordon(JO)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Kazakhstan(KZ)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Kenya(KE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Kuwait(KW)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Lesotho(LS)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Mauritius(MU)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Morocco(MA)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Mozambique(MZ)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Oman(OM)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Qatar(QA)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Saudi Arabia(SA)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "Senegal(SN)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "South Africa(ZA)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Upfront Onboarding - Casual Seller - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding (PayPal)",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "BMW",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],
        [
            "name" => "United Arab Emirates(AE)",
            "sublists" => [
                "Upfront Onboarding - Business Account - Branded",
                "Progressive Onboarding - Business Account - Branded",
                "Managed Path Onboarding (PayPal)",
                "PayPal",
                "Inline Guest(BCDC) (Buyer Country)",
                "Partner Fee (Partner Country)- US Bank",
                "Flexible Partner Fee Refunds",
                "Multi-seller Payments (MSP)",
                "PSP - Partner Specific Pricing",
                "Partner Defined Tiered Pricing",
                "Payouts (Sender Country)",
                "Payouts (Receiver Country)",
                "Invoicing APIs (Buyer Country) - PayPal, BCDC",
                "Subscription APIs - PayPal",
            ],
        ],










    ]
]; 
?>

