<?php $data = [
    "lists" => [
        [
            "name" => "United States(US)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Venmo",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT,DE",
                "Pay Later Messaging",
                "PPC Buyer Country",
                "Vaulting - PP, Cards,Venmo, AP",
                "Fastlane",
                "Apple Pay",
                "Google Pay",
                "ACH",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Canada(CA)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Fastlane - 2025",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "United Kingdom(GB)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT,DE",
                "Pay Later Messaging ",
                "PPC Buyer Country",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Fastlane - 2025",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Austria(AT)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (eps)",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Belgium(BE)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Bancontact)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Bulgaria(BG)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Cyprus(CY)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Czech Republic(CZ)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Denmark(DK)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Estonia(EE)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Finland(FI)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "France(FR)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging ",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Germany(DE)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT,DE",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Greece(GR)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging ",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (PUI)",
                "Local APM - (Trustly)",
                "Fastlane - 2025",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Hungary(HU)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Ireland(IE)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "MCP",
            ],
        ],
        [
            "name" => "Italy(IT)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging ",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (MyBank)",
                "Fastlane - 2025",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Latvia(LT)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Liechtenstein(LI)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Lithuania(LT)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Luxembourg(LU)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Malta(MT)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Netherlands(NL)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (iDEAL)",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Norway(NO)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Poland(PL)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Blik, P24)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Portugal(PT)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Multibanco)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Romania(RO)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Slovakia(SK)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Slovenia(SI)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Spain(ES)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging ",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Sweden(SE)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Trustly)",
                "Apple Pay",
                "Google Pay",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "3PNT - Beta",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "Andorra(AD)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Croatia(HR)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "MCP",
            ],
        ],
        [
            "name" => "Guernsey(GG)",
            "sublists" => ["Braintree", "Hyperwallet - Payee Country"],
        ],
        [
            "name" => "Iceland(IS)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Isle of Man(IM)",
            "sublists" => ["Braintree", "Hyperwallet - Payee Country"],
        ],
        [
            "name" => "Jersey(JE)",
            "sublists" => ["Braintree", "Hyperwallet - Payee Country"],
        ],
        [
            "name" => "Monaco(MC)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "San Marino(SM)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Switzerland(CH)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Australia(AU)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging ",
                "Vaulting - PP, Cards,Venmo, AP",
                "Fastlane - 2025",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
                "IC++ Pricing",
                "MCP",
            ],
        ],
        [
            "name" => "China(CN)",
            "sublists" => [
                "PayPal",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Alipay)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Hong Kong(HK)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "3PNT - 2025",
                "Hyperwallet - Payee Country",
                "IC++ Pricing",
            ],
        ],
        [
            "name" => "India(IN)",
            "sublists" => [
                "PayPal - Cross Border Only",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Indonesia(ID)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Japan(JP)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Korea(KR)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Malaysia(MY)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "New Zealand(NZ)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "New Zealand(NZ)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Singapore(SG)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Advanced Cards - ACDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Vaulting - PP, Cards,Venmo, AP",
                "Local APM - (Grabpay)",
                "Apple Pay",
                "Google Pay",
                "NBW",
                "MCW",
                "Hyperwallet - Payee Country",
                "3PNT - 2025",
                "IC++ Pricing",
            ],
        ],
        [
            "name" => "Taiwan(TW)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "BMW",
                "MCW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Thailand(TH)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Vietnam(VN)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "MCW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Brazil(BR)",
            "sublists" => [
                "PayPal",
                "Braintree",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Local APM - (Boleto)",
                "Zettle POS",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Mexico(MX)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Local APM - (XOXO)",
                "Zettle POS",
                "NBW",
                "MCW",
                "Mass Pay(OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Argentina(AR)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Colombia(CO)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Peru(PE)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Chile(CL)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Bahrain(BH)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Botswana(BW)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Egypty(EG)",
            "sublists" => [
                "PayPal(Zero)",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Georgia(GE)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Jordon(JO)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Kazakhstan(KZ)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Kenya(KE)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Kuwait(KW)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Lesotho(LS)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Mauritius(MU)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Morocco(MA)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Mozombique(MZ)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Oman(OM)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Qatar(QA)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Saudi Arabia(SA)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "Senegal(SN)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "South Africa(SA)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "BMW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
        [
            "name" => "United Arab Emirates(AE)",
            "sublists" => [
                "PayPal",
                "Inline Guest - BCDC",
                "Pay Later Buyer Countries - US,AU,UK,ES,FR,IT",
                "Pay Later Messaging (Cross Border)",
                "NBW",
                "Mass Pay(IN/OUT)",
                "Hyperwallet - Payee Country",
            ],
        ],
    ]
];
?>
